application: kx-tutor-hangout-app
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/docs/.json
  upload: static/docs\.json

- url: /js
  mime_type: text/javascript
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /.*
  script: main.application

- url: /subjects.*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
