application: kx-tutor-hangout-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /views
  static_dir: views/

- url: /js
  mime_type: text/javascript
  static_dir: static/js

- url: /css
  static_dir: static/css


- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

# Endpoints handler
- url: /_ah/spi/.*
  script: tutor_hangouts_api.app

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: endpoints
  version: 1.0
- name: jinja2
  version: 2.6
